server:
  port: 7550

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: rvi_analyzer
#      username: rviUser
#      password: password

jwt:
  secretKey: "thisWasSecurityKeyUsedForMakingJWTKeys"
  validityInMs: 60000
  password:
    encoder:
      secret: rviAnalyzerKey
      iteration: 33
      key-length: 256

